# $schema: https://json.schemastore.org/github-workflow.json
name: Update Package Repo

on:
  workflow_call:
    inputs:
      signing-key-name:
        description: "The name of the key used to sign the package index (not including the .rsa/.rsa.pub suffix)"
        required: false
        type: string
        default: ""
      environment:
        description: The environment to use when deploying to GitHub Pages
        type: string
        default: "package-repo"
    secrets:
      signing-key:
        description: "The private key used to sign the package index (PEM format)"
        required: false

permissions: {}

jobs:
  build:
    name: Build package repo

    runs-on: ubuntu-24.04

    permissions:
      contents: read  # to get packages from Releases

    steps:
      - name: Setup melange
        uses: rbrownwsws/setup-melange@b4f5fbf8089c1b0edef0d90f89f53a048dfe5c13 # v1.0.2

      - name: Create package repo
        id: create-repo
        uses: rbrownwsws/create-melange-package-repo@0366a92692189adbd99c744589f5b3dd3ab5bb95 # v1.0.0
        with:
          signing-key: ${{ secrets.signing-key }}
          signing-key-name: ${{ inputs.signing-key-name }}

      - name: Create package repo index pages
        uses: rbrownwsws/create-melange-package-repo-index-pages@85ff986d719856b5ee280430b958ea68c74a43f0 # v1.0.3
        with:
          repo-dir: ${{ steps.create-repo.outputs.repo-dir }}

      - name: Upload package repo as artifact
        id: deployment
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ${{ steps.create-repo.outputs.repo-dir }}

  deploy:
    name: Deploy package repo to GitHub Pages

    needs: build

    runs-on: ubuntu-24.04

    permissions:
      pages: write     # to deploy to Pages
      id-token: write  # to verify the deployment originates from an appropriate source

    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
